// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.

export type Variant = {
  sku: string;
  label: string;
  color: string;
  size: string;
  price: number;
  quantity: number;
  image: string;
};

export type Product = {
  id: string;
  name: string;
  brand: string;
  category_1: string;
  category_2: string;
  description: string;
  material: string;
  gender: string;
  price: number;
  currency: string;
  rating_value?: number;
  rating_count?: number;
  image: string;
  variants: Variant[];
};

export const CATEGORIES: string[] = ["Apparel","Footwear","Accessories"];

export const PRODUCTS: Product[] = [
  {
    "id": "TSHIRT-001",
    "name": "Classic Vintage Tee",
    "brand": "Adidas",
    "category_1": "Apparel",
    "category_2": "T-Shirts",
    "description": "Washed vintage crewneck t-shirt in premium heavy organic cotton. Features a relaxed structured fit with soft retro ribbing.",
    "material": "100% Organic Cotton",
    "gender": "unisex",
    "price": 29.99,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 312,
    "image": "tshirt-red.jpg",
    "variants": [
      {
        "sku": "TSHIRT-001-RED-M",
        "label": "Red / M",
        "color": "Red",
        "size": "M",
        "price": 29.99,
        "quantity": 50,
        "image": "tshirt-red.jpg"
      },
      {
        "sku": "TSHIRT-001-RED-L",
        "label": "Red / L",
        "color": "Red",
        "size": "L",
        "price": 29.99,
        "quantity": 45,
        "image": "tshirt-red.jpg"
      },
      {
        "sku": "TSHIRT-001-BLK-M",
        "label": "Black / M",
        "color": "Black",
        "size": "M",
        "price": 29.99,
        "quantity": 30,
        "image": "tshirt-black.jpg"
      }
    ]
  },
  {
    "id": "SHIRT-002",
    "name": "Linen Button-Up",
    "brand": "Uniqlo",
    "category_1": "Apparel",
    "category_2": "Shirts",
    "description": "Premium woven linen button-up shirt in a comfortable airy cut. Breathable and cool, perfect for lightweight layering.",
    "material": "100% Woven Linen",
    "gender": "men",
    "price": 49.99,
    "currency": "EUR",
    "rating_value": 4.3,
    "rating_count": 267,
    "image": "shirt-white.jpg",
    "variants": [
      {
        "sku": "SHIRT-002-WHT-M",
        "label": "White / M",
        "color": "White",
        "size": "M",
        "price": 49.99,
        "quantity": 35,
        "image": "shirt-white.jpg"
      },
      {
        "sku": "SHIRT-002-BLU-L",
        "label": "Blue / L",
        "color": "Blue",
        "size": "L",
        "price": 49.99,
        "quantity": 28,
        "image": "shirt-blue.jpg"
      }
    ]
  },
  {
    "id": "HOODIE-003",
    "name": "Premium Fleece Hoodie",
    "brand": "Champion",
    "category_1": "Apparel",
    "category_2": "Sweatshirts",
    "description": "Heavyweight organic cotton fleece pullover hoodie with double-needle tailoring, cozy front pouch pocket, and retro ribbed hem.",
    "material": "80% Organic Cotton 20% Poly",
    "gender": "unisex",
    "price": 69.99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 403,
    "image": "hoodie-grey.jpg",
    "variants": [
      {
        "sku": "HOODIE-003-GRY-M",
        "label": "Grey / M",
        "color": "Grey",
        "size": "M",
        "price": 69.99,
        "quantity": 22,
        "image": "hoodie-grey.jpg"
      },
      {
        "sku": "HOODIE-003-GRY-L",
        "label": "Grey / L",
        "color": "Grey",
        "size": "L",
        "price": 69.99,
        "quantity": 18,
        "image": "hoodie-grey.jpg"
      },
      {
        "sku": "HOODIE-003-NVY-M",
        "label": "Navy / M",
        "color": "Navy",
        "size": "M",
        "price": 69.99,
        "quantity": 14,
        "image": "hoodie-navy.jpg"
      }
    ]
  },
  {
    "id": "JACKET-004",
    "name": "Classic Bomber Jacket",
    "brand": "The North Face",
    "category_1": "Apparel",
    "category_2": "Jackets",
    "description": "Ultra-durable weather-resistant bomber jacket featuring clean geometric quilting, micro-knit ribbed collar, and secure side pockets.",
    "material": "Nylon Shell Quilting",
    "gender": "unisex",
    "price": 179.99,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 512,
    "image": "jacket-black.jpg",
    "variants": [
      {
        "sku": "JACKET-004-BLK-M",
        "label": "Black / M",
        "color": "Black",
        "size": "M",
        "price": 179.99,
        "quantity": 12,
        "image": "jacket-black.jpg"
      },
      {
        "sku": "JACKET-004-GRN-L",
        "label": "Green / L",
        "color": "Green",
        "size": "L",
        "price": 179.99,
        "quantity": 9,
        "image": "jacket-green.jpg"
      }
    ]
  },
  {
    "id": "JEANS-005",
    "name": "Slim Fit Denim Jeans",
    "brand": "Levi's",
    "category_1": "Apparel",
    "category_2": "Trousers",
    "description": "Slim-fit five-pocket denim jeans with natural indigo wash fading, durable copper rivets, and a comfortable touch of stretch.",
    "material": "98% Cotton 2% Elastane",
    "gender": "men",
    "price": 59.99,
    "currency": "EUR",
    "rating_value": 4.4,
    "rating_count": 587,
    "image": "jeans-blue.jpg",
    "variants": [
      {
        "sku": "JEANS-005-BLU-32",
        "label": "Blue / 32",
        "color": "Blue",
        "size": "32",
        "price": 59.99,
        "quantity": 20,
        "image": "jeans-blue.jpg"
      },
      {
        "sku": "JEANS-005-BLU-34",
        "label": "Blue / 34",
        "color": "Blue",
        "size": "34",
        "price": 59.99,
        "quantity": 25,
        "image": "jeans-blue.jpg"
      },
      {
        "sku": "JEANS-005-BLK-32",
        "label": "Black / 32",
        "color": "Black",
        "size": "32",
        "price": 59.99,
        "quantity": 30,
        "image": "jeans-black.jpg"
      }
    ]
  },
  {
    "id": "CHINO-006",
    "name": "Tailored Chino Trousers",
    "brand": "Dockers",
    "category_1": "Apparel",
    "category_2": "Trousers",
    "description": "Slim-tapered tailored chinos crafted in washed soft cotton twill weave, featuring natural stretch, back welt pockets, and clean flat front.",
    "material": "97% Brushed Twill Cotton",
    "gender": "men",
    "price": 69.99,
    "currency": "EUR",
    "rating_value": 4.2,
    "rating_count": 194,
    "image": "chino-beige.jpg",
    "variants": [
      {
        "sku": "CHINO-006-BEI-32",
        "label": "Beige / 32",
        "color": "Beige",
        "size": "32",
        "price": 69.99,
        "quantity": 30,
        "image": "chino-beige.jpg"
      },
      {
        "sku": "CHINO-006-NVY-34",
        "label": "Navy / 34",
        "color": "Navy",
        "size": "34",
        "price": 69.99,
        "quantity": 25,
        "image": "chino-navy.jpg"
      }
    ]
  },
  {
    "id": "SHORTS-007",
    "name": "Everyday Utility Shorts",
    "brand": "Patagonia",
    "category_1": "Apparel",
    "category_2": "Shorts",
    "description": "Rugged lightweight utility shorts in weather-resistant recycled nylon twill, featuring secure snap pockets and a comfortable active waist.",
    "material": "100% Recycled Nylon",
    "gender": "unisex",
    "price": 49.99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 215,
    "image": "shorts-khaki.jpg",
    "variants": [
      {
        "sku": "SHORTS-007-KHA-32",
        "label": "Khaki / 32",
        "color": "Khaki",
        "size": "32",
        "price": 49.99,
        "quantity": 32,
        "image": "shorts-khaki.jpg"
      },
      {
        "sku": "SHORTS-007-BLK-34",
        "label": "Black / 34",
        "color": "Black",
        "size": "34",
        "price": 49.99,
        "quantity": 28,
        "image": "shorts-black.jpg"
      }
    ]
  },
  {
    "id": "SHOE-003",
    "name": "Urban Street Sneakers",
    "brand": "Nike",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Minimalist low-profile street sneakers featuring a full-grain leather upper, mesh lining, cushioned EVA midsole, and high-grip rubber outsole.",
    "material": "Full-Grain Leather & Mesh",
    "gender": "unisex",
    "price": 89.99,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 892,
    "image": "sneakers-white.jpg",
    "variants": [
      {
        "sku": "SHOE-003-WHT-42",
        "label": "White / 42",
        "color": "White",
        "size": "42",
        "price": 89.99,
        "quantity": 10,
        "image": "sneakers-white.jpg"
      },
      {
        "sku": "SHOE-003-WHT-43",
        "label": "White / 43",
        "color": "White",
        "size": "43",
        "price": 89.99,
        "quantity": 12,
        "image": "sneakers-white.jpg"
      },
      {
        "sku": "SHOE-003-BLK-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 89.99,
        "quantity": 8,
        "image": "sneakers-black.jpg"
      },
      {
        "sku": "SHOE-003-BLK-43",
        "label": "Black / 43",
        "color": "Black",
        "size": "43",
        "price": 89.99,
        "quantity": 12,
        "image": "sneakers-black.jpg"
      }
    ]
  },
  {
    "id": "BOOT-010",
    "name": "Leather Chelsea Boots",
    "brand": "Dr. Martens",
    "category_1": "Footwear",
    "category_2": "Boots",
    "description": "Sleek classic Chelsea boots in oil-tanned top-grain leather with elastic side panels, Goodyear welt stitching, and comfortable cushioned soles.",
    "material": "Top-Grain Waxed Leather",
    "gender": "unisex",
    "price": 189,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 673,
    "image": "boots-black.jpg",
    "variants": [
      {
        "sku": "BOOT-010-BLK-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 189,
        "quantity": 8,
        "image": "boots-black.jpg"
      },
      {
        "sku": "BOOT-010-BRN-43",
        "label": "Brown / 43",
        "color": "Brown",
        "size": "43",
        "price": 189,
        "quantity": 6,
        "image": "boots-brown.jpg"
      }
    ]
  },
  {
    "id": "SANDAL-011",
    "name": "Cork Footbed Sandals",
    "brand": "Birkenstock",
    "category_1": "Footwear",
    "category_2": "Sandals",
    "description": "Ergonomic cork-latex footbed slide sandals with dual adjustable oiled-leather straps and deep heel cup support.",
    "material": "Oiled Leather & Cork",
    "gender": "unisex",
    "price": 99.99,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 348,
    "image": "sandals-brown.jpg",
    "variants": [
      {
        "sku": "SANDAL-011-BRN-41",
        "label": "Brown / 41",
        "color": "Brown",
        "size": "41",
        "price": 99.99,
        "quantity": 15,
        "image": "sandals-brown.jpg"
      },
      {
        "sku": "SANDAL-011-BLK-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 99.99,
        "quantity": 14,
        "image": "sandals-black.jpg"
      }
    ]
  },
  {
    "id": "WATCH-012",
    "name": "Silver Chronograph Watch",
    "brand": "Seiko",
    "category_1": "Accessories",
    "category_2": "Watches",
    "description": "Polished stainless steel mechanical chronograph watch with three detailed sub-dials, date window, and scratch-resistant crystal face.",
    "material": "Stainless Steel",
    "gender": "men",
    "price": 249,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 289,
    "image": "watch-silver.jpg",
    "variants": [
      {
        "sku": "WATCH-012-SLV",
        "label": "Silver",
        "color": "Silver",
        "size": "One Size",
        "price": 249,
        "quantity": 7,
        "image": "watch-silver.jpg"
      }
    ]
  },
  {
    "id": "ACC-004",
    "name": "Classic Gold Watch",
    "brand": "Casio",
    "category_1": "Accessories",
    "category_2": "Watches",
    "description": "Timeless gold-plated minimalist wristwatch featuring an analog sweep second hand, quartz movement, and premium case detailing.",
    "material": "Gold-Plated Stainless Steel",
    "gender": "unisex",
    "price": 120,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 221,
    "image": "watch-gold.png",
    "variants": [
      {
        "sku": "ACC-004-GLD",
        "label": "Gold",
        "color": "Gold",
        "size": "One Size",
        "price": 120,
        "quantity": 15,
        "image": "watch-gold.png"
      }
    ]
  },
  {
    "id": "ACC-005",
    "name": "Premium Leather Belt",
    "brand": "Gucci",
    "category_1": "Accessories",
    "category_2": "Belts",
    "description": "Luxurious hand-finished leather belt crafted in rich calfskin, featuring a double-ring metal buckle and durable edge-stitch detailing.",
    "material": "100% Genuine Calfskin",
    "gender": "men",
    "price": 150,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 156,
    "image": "belt-black.jpg",
    "variants": [
      {
        "sku": "ACC-005-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 150,
        "quantity": 5,
        "image": "belt-black.jpg"
      },
      {
        "sku": "ACC-005-BRN",
        "label": "Brown",
        "color": "Brown",
        "size": "One Size",
        "price": 150,
        "quantity": 8,
        "image": "belt-brown.jpg"
      }
    ]
  },
  {
    "id": "BAG-013",
    "name": "Pebbled Crossbody Bag",
    "brand": "Coach",
    "category_1": "Accessories",
    "category_2": "Bags",
    "description": "Sleek crossbody handbag in rich pebbled calf leather featuring matching adjustable shoulder strap and polished metal buckle closures.",
    "material": "Pebbled Calf Leather",
    "gender": "women",
    "price": 229,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 402,
    "image": "bag-black.jpg",
    "variants": [
      {
        "sku": "BAG-013-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 229,
        "quantity": 11,
        "image": "bag-black.jpg"
      },
      {
        "sku": "BAG-013-BRN",
        "label": "Brown",
        "color": "Brown",
        "size": "One Size",
        "price": 229,
        "quantity": 9,
        "image": "bag-brown.jpg"
      }
    ]
  },
  {
    "id": "WALLET-014",
    "name": "Bifold Leather Wallet",
    "brand": "Tommy Hilfiger",
    "category_1": "Accessories",
    "category_2": "Wallets",
    "description": "Classic slim-structured bifold leather wallet in top-grain calfskin, featuring multiple card slots, bill compartment, and built-in RFID blocker.",
    "material": "100% Genuine Bovine Leather",
    "gender": "men",
    "price": 79,
    "currency": "EUR",
    "rating_value": 4.4,
    "rating_count": 521,
    "image": "wallet-black.jpg",
    "variants": [
      {
        "sku": "WALLET-014-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 79,
        "quantity": 40,
        "image": "wallet-black.jpg"
      },
      {
        "sku": "WALLET-014-BRN",
        "label": "Brown",
        "color": "Brown",
        "size": "One Size",
        "price": 79,
        "quantity": 35,
        "image": "wallet-brown.jpg"
      }
    ]
  },
  {
    "id": "BACKPACK-015",
    "name": "Urban Travel Backpack",
    "brand": "Herschel",
    "category_1": "Accessories",
    "category_2": "Bags",
    "description": "Robust urban travel pack in weather-resistant poly twill, featuring padded protective laptop sleeve and secure buckle closures.",
    "material": "600D Weatherproof Poly",
    "gender": "unisex",
    "price": 129,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 592,
    "image": "backpack-grey.jpg",
    "variants": [
      {
        "sku": "BACKPACK-015-GRY",
        "label": "Grey",
        "color": "Grey",
        "size": "One Size",
        "price": 129,
        "quantity": 16,
        "image": "backpack-grey.jpg"
      },
      {
        "sku": "BACKPACK-015-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 129,
        "quantity": 12,
        "image": "backpack-black.jpg"
      }
    ]
  },
  {
    "id": "RUNNER-016",
    "name": "Primeknit Running Shoes",
    "brand": "Adidas",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "High-performance running shoes crafted in breathable Primeknit mesh with responsive foam cushioning and high-grip rubber outsole.",
    "material": "Recycled Primeknit Mesh",
    "gender": "unisex",
    "price": 119.99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 463,
    "image": "runner-black.jpg",
    "variants": [
      {
        "sku": "RUNNER-016-BLK-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 119.99,
        "quantity": 20,
        "image": "runner-black.jpg"
      },
      {
        "sku": "RUNNER-016-BLK-43",
        "label": "Black / 43",
        "color": "Black",
        "size": "43",
        "price": 119.99,
        "quantity": 16,
        "image": "runner-black.jpg"
      }
    ]
  },
  {
    "id": "SWEATER-017",
    "name": "Beige Knit Sweater",
    "brand": "Everlane",
    "category_1": "Apparel",
    "category_2": "Knitwear",
    "description": "Relaxed slouchy knit sweater crafted from a premium merino wool blend. Features a cozy ribbed crewneck and drop shoulders for an elegant drape.",
    "material": "80% Merino Wool 20% Nylon",
    "gender": "unisex",
    "price": 89.99,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 124,
    "image": "sweater-beige.jpg",
    "variants": [
      {
        "sku": "SWEATER-017-BEI-M",
        "label": "Beige / M",
        "color": "Beige",
        "size": "M",
        "price": 89.99,
        "quantity": 25,
        "image": "sweater-beige.jpg"
      },
      {
        "sku": "SWEATER-017-BEI-L",
        "label": "Beige / L",
        "color": "Beige",
        "size": "L",
        "price": 89.99,
        "quantity": 25,
        "image": "sweater-beige.jpg"
      }
    ]
  },
  {
    "id": "SKIRT-018",
    "name": "Plaid Pleated Skirt",
    "brand": "Zara",
    "category_1": "Apparel",
    "category_2": "Skirts",
    "description": "High-waisted pleated skirt featuring a classic heritage plaid check pattern. Crafted in structured woven wool blend fabric with side zip closure.",
    "material": "60% Wool 40% Polyester",
    "gender": "women",
    "price": 49.99,
    "currency": "EUR",
    "rating_value": 4.4,
    "rating_count": 98,
    "image": "skirt-plaid.jpg",
    "variants": [
      {
        "sku": "SKIRT-018-PLA-S",
        "label": "Plaid / S",
        "color": "Plaid",
        "size": "S",
        "price": 49.99,
        "quantity": 25,
        "image": "skirt-plaid.jpg"
      },
      {
        "sku": "SKIRT-018-PLA-M",
        "label": "Plaid / M",
        "color": "Plaid",
        "size": "M",
        "price": 49.99,
        "quantity": 25,
        "image": "skirt-plaid.jpg"
      }
    ]
  },
  {
    "id": "BLAZER-019",
    "name": "Structured Wool Blazer",
    "brand": "Mango",
    "category_1": "Apparel",
    "category_2": "Jackets",
    "description": "Tailored double-breasted blazer in a luxurious brushed wool blend. Designed with defined structured shoulders, peak lapels, and tortoiseshell buttons.",
    "material": "70% Wool 30% Viscose",
    "gender": "women",
    "price": 149.99,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 83,
    "image": "blazer-wool.jpg",
    "variants": [
      {
        "sku": "BLAZER-019-BRO-M",
        "label": "Brown / M",
        "color": "Brown",
        "size": "M",
        "price": 149.99,
        "quantity": 25,
        "image": "blazer-wool.jpg"
      },
      {
        "sku": "BLAZER-019-BRO-L",
        "label": "Brown / L",
        "color": "Brown",
        "size": "L",
        "price": 149.99,
        "quantity": 25,
        "image": "blazer-wool.jpg"
      }
    ]
  },
  {
    "id": "TRENCH-020",
    "name": "Classic Camel Trench Coat",
    "brand": "Burberry",
    "category_1": "Apparel",
    "category_2": "Jackets",
    "description": "Double-breasted trench coat in water-resistant heavy cotton gabardine. Detailed with buttoned epaulets, adjustable storm flaps, and a matching waist belt.",
    "material": "100% Cotton Gabardine",
    "gender": "unisex",
    "price": 299.99,
    "currency": "EUR",
    "rating_value": 4.9,
    "rating_count": 156,
    "image": "trench-camel.jpg",
    "variants": [
      {
        "sku": "TRENCH-020-CAM-M",
        "label": "Camel / M",
        "color": "Camel",
        "size": "M",
        "price": 299.99,
        "quantity": 25,
        "image": "trench-camel.jpg"
      },
      {
        "sku": "TRENCH-020-CAM-L",
        "label": "Camel / L",
        "color": "Camel",
        "size": "L",
        "price": 299.99,
        "quantity": 25,
        "image": "trench-camel.jpg"
      }
    ]
  },
  {
    "id": "SWEATER-021",
    "name": "Cable Knit Sweater",
    "brand": "Polo Ralph Lauren",
    "category_1": "Apparel",
    "category_2": "Knitwear",
    "description": "Traditional heavyweight cable-knit sweater made from ultra-soft organic cotton. Features an authentic chunky fisherman braid texture and thick ribbed trim.",
    "material": "100% Organic Cotton",
    "gender": "unisex",
    "price": 120,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 210,
    "image": "sweater-cable.jpg",
    "variants": [
      {
        "sku": "SWEATER-021-WHI-M",
        "label": "White / M",
        "color": "White",
        "size": "M",
        "price": 120,
        "quantity": 25,
        "image": "sweater-cable.jpg"
      },
      {
        "sku": "SWEATER-021-WHI-L",
        "label": "White / L",
        "color": "White",
        "size": "L",
        "price": 120,
        "quantity": 25,
        "image": "sweater-cable.jpg"
      }
    ]
  },
  {
    "id": "DRESS-022",
    "name": "Floral Summer Dress",
    "brand": "H&M",
    "category_1": "Apparel",
    "category_2": "Dresses",
    "description": "Flowing mid-length summer dress featuring a delicate hand-painted floral pattern. Crafted from breathable airy viscose with adjustable tie shoulder straps.",
    "material": "100% Viscose",
    "gender": "women",
    "price": 39.99,
    "currency": "EUR",
    "rating_value": 4.3,
    "rating_count": 142,
    "image": "dress-floral.jpg",
    "variants": [
      {
        "sku": "DRESS-022-FLO-S",
        "label": "Floral / S",
        "color": "Floral",
        "size": "S",
        "price": 39.99,
        "quantity": 25,
        "image": "dress-floral.jpg"
      },
      {
        "sku": "DRESS-022-FLO-M",
        "label": "Floral / M",
        "color": "Floral",
        "size": "M",
        "price": 39.99,
        "quantity": 25,
        "image": "dress-floral.jpg"
      }
    ]
  },
  {
    "id": "CARGO-023",
    "name": "Cargo Utility Pants",
    "brand": "Carhartt WIP",
    "category_1": "Apparel",
    "category_2": "Trousers",
    "description": "Rugged cargo pants cut in a modern relaxed taper from heavy cotton ripstop. Features double-reinforced knees, deep side bellows utility pockets, and adjustable hems.",
    "material": "100% Cotton Ripstop",
    "gender": "men",
    "price": 110,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 188,
    "image": "cargo-khaki.jpg",
    "variants": [
      {
        "sku": "CARGO-023-KHA-32",
        "label": "Khaki / 32",
        "color": "Khaki",
        "size": "32",
        "price": 110,
        "quantity": 25,
        "image": "cargo-khaki.jpg"
      },
      {
        "sku": "CARGO-023-KHA-34",
        "label": "Khaki / 34",
        "color": "Khaki",
        "size": "34",
        "price": 110,
        "quantity": 25,
        "image": "cargo-khaki.jpg"
      }
    ]
  },
  {
    "id": "CARDIGAN-024",
    "name": "Cozy Knit Cardigan",
    "brand": "Oak + Fort",
    "category_1": "Apparel",
    "category_2": "Knitwear",
    "description": "Open-front oversized longline cardigan knitted in super-soft mohair blend wool. Detailed with two roomy front patch pockets and elegant ribbed cuffs.",
    "material": "50% Mohair 30% Acrylic 20% Wool",
    "gender": "women",
    "price": 79.99,
    "currency": "EUR",
    "rating_value": 4.2,
    "rating_count": 75,
    "image": "cardigan-grey.jpg",
    "variants": [
      {
        "sku": "CARDIGAN-024-GRE-M",
        "label": "Grey / M",
        "color": "Grey",
        "size": "M",
        "price": 79.99,
        "quantity": 25,
        "image": "cardigan-grey.jpg"
      },
      {
        "sku": "CARDIGAN-024-GRE-L",
        "label": "Grey / L",
        "color": "Grey",
        "size": "L",
        "price": 79.99,
        "quantity": 25,
        "image": "cardigan-grey.jpg"
      }
    ]
  },
  {
    "id": "POLO-025",
    "name": "Knit Polo Shirt",
    "brand": "Fred Perry",
    "category_1": "Apparel",
    "category_2": "Shirts",
    "description": "Retro-style short sleeve knit polo shirt in dynamic textured piqué cotton stitch. Designed with a clean flat collar, three-button placket, and ribbed hem.",
    "material": "100% Pique Cotton",
    "gender": "men",
    "price": 95,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 119,
    "image": "polo-knit.jpg",
    "variants": [
      {
        "sku": "POLO-025-BLU-M",
        "label": "Blue / M",
        "color": "Blue",
        "size": "M",
        "price": 95,
        "quantity": 25,
        "image": "polo-knit.jpg"
      },
      {
        "sku": "POLO-025-BLU-L",
        "label": "Blue / L",
        "color": "Blue",
        "size": "L",
        "price": 95,
        "quantity": 25,
        "image": "polo-knit.jpg"
      }
    ]
  },
  {
    "id": "WINDBREAKER-026",
    "name": "Sport Windbreaker Jacket",
    "brand": "Patagonia",
    "category_1": "Apparel",
    "category_2": "Jackets",
    "description": "Lightweight weather-proof windbreaker jacket engineered from tear-resistant technical nylon. Features adjustable drawcord hood, elasticated cuffs, and reflective piping details.",
    "material": "100% Recycled Nylon",
    "gender": "unisex",
    "price": 139,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 165,
    "image": "windbreaker-sport.jpg",
    "variants": [
      {
        "sku": "WINDBREAKER-026-BLA-M",
        "label": "Black / M",
        "color": "Black",
        "size": "M",
        "price": 139,
        "quantity": 25,
        "image": "windbreaker-sport.jpg"
      },
      {
        "sku": "WINDBREAKER-026-BLA-L",
        "label": "Black / L",
        "color": "Black",
        "size": "L",
        "price": 139,
        "quantity": 25,
        "image": "windbreaker-sport.jpg"
      }
    ]
  },
  {
    "id": "OXFORD-027",
    "name": "Classic Leather Oxfords",
    "brand": "Clarks",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Timeless formal Oxford dress shoes crafted from hand-burnished Italian calfskin leather. Featuring elegant closed-lace design and a durable Goodyear welted sole.",
    "material": "Italian Calfskin Leather",
    "gender": "men",
    "price": 129.99,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 112,
    "image": "oxfords-leather.jpg",
    "variants": [
      {
        "sku": "OXFORD-027-BRO-42",
        "label": "Brown / 42",
        "color": "Brown",
        "size": "42",
        "price": 129.99,
        "quantity": 25,
        "image": "oxfords-leather.jpg"
      },
      {
        "sku": "OXFORD-027-BRO-43",
        "label": "Brown / 43",
        "color": "Brown",
        "size": "43",
        "price": 129.99,
        "quantity": 25,
        "image": "oxfords-leather.jpg"
      }
    ]
  },
  {
    "id": "HEELS-028",
    "name": "Red Velvet Stiletto Heels",
    "brand": "Steve Madden",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Seductive pointed-toe stiletto pump heels wrapped in luxurious deep crimson velvet. Finished with a cushioned leather insole and slim 4-inch heel structure.",
    "material": "Velvet Upper & Leather Sole",
    "gender": "women",
    "price": 99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 94,
    "image": "heels-red.jpg",
    "variants": [
      {
        "sku": "HEELS-028-RED-38",
        "label": "Red / 38",
        "color": "Red",
        "size": "38",
        "price": 99,
        "quantity": 25,
        "image": "heels-red.jpg"
      },
      {
        "sku": "HEELS-028-RED-39",
        "label": "Red / 39",
        "color": "Red",
        "size": "39",
        "price": 99,
        "quantity": 25,
        "image": "heels-red.jpg"
      }
    ]
  },
  {
    "id": "LOAFER-029",
    "name": "Suede Penny Loafers",
    "brand": "G.H. Bass",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Refined slip-on penny loafers in premium water-repellent English suede. Built with a moccasin-stitched toe, traditional strap detail, and flexible leather outsole.",
    "material": "English Suede Leather",
    "gender": "men",
    "price": 140,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 135,
    "image": "loafers-suede.jpg",
    "variants": [
      {
        "sku": "LOAFER-029-TAN-42",
        "label": "Tan / 42",
        "color": "Tan",
        "size": "42",
        "price": 140,
        "quantity": 25,
        "image": "loafers-suede.jpg"
      },
      {
        "sku": "LOAFER-029-TAN-43",
        "label": "Tan / 43",
        "color": "Tan",
        "size": "43",
        "price": 140,
        "quantity": 25,
        "image": "loafers-suede.jpg"
      }
    ]
  },
  {
    "id": "HIKING-030",
    "name": "Leather Hiking Boots",
    "brand": "Timberland",
    "category_1": "Footwear",
    "category_2": "Boots",
    "description": "Heavy-duty outdoor hiking boots built with waterproof nubuck leather upper and durable metal D-ring speed lacing. Grounded by a heavy-lug Vibram rubber tread.",
    "material": "Nubuck Leather & Vibram Rubber",
    "gender": "unisex",
    "price": 169.99,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 247,
    "image": "hiking-boots.jpg",
    "variants": [
      {
        "sku": "HIKING-030-BRO-42",
        "label": "Brown / 42",
        "color": "Brown",
        "size": "42",
        "price": 169.99,
        "quantity": 25,
        "image": "hiking-boots.jpg"
      },
      {
        "sku": "HIKING-030-BRO-43",
        "label": "Brown / 43",
        "color": "Brown",
        "size": "43",
        "price": 169.99,
        "quantity": 25,
        "image": "hiking-boots.jpg"
      }
    ]
  },
  {
    "id": "SLIPPER-031",
    "name": "Cozy Shearling Slippers",
    "brand": "UGG",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Luxurious indoor slippers crafted from ultra-soft suede lined with genuine Australian shearling sheepskin for ultimate warmth and plush underfoot comfort.",
    "material": "Suede & Australian Shearling",
    "gender": "unisex",
    "price": 89.99,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 312,
    "image": "slippers-shearling.jpg",
    "variants": [
      {
        "sku": "SLIPPER-031-BEI-40",
        "label": "Beige / 40",
        "color": "Beige",
        "size": "40",
        "price": 89.99,
        "quantity": 25,
        "image": "slippers-shearling.jpg"
      },
      {
        "sku": "SLIPPER-031-BEI-42",
        "label": "Beige / 42",
        "color": "Beige",
        "size": "42",
        "price": 89.99,
        "quantity": 25,
        "image": "slippers-shearling.jpg"
      }
    ]
  },
  {
    "id": "BROGUE-032",
    "name": "Tan Leather Brogues",
    "brand": "Cole Haan",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Smart tan calfskin leather brogue shoes boasting traditional wingtip perforation details, decorative punching, and a robust stacked heel.",
    "material": "Full-Grain Calfskin Leather",
    "gender": "men",
    "price": 159,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 89,
    "image": "brogues-tan.jpg",
    "variants": [
      {
        "sku": "BROGUE-032-TAN-42",
        "label": "Tan / 42",
        "color": "Tan",
        "size": "42",
        "price": 159,
        "quantity": 25,
        "image": "brogues-tan.jpg"
      },
      {
        "sku": "BROGUE-032-TAN-43",
        "label": "Tan / 43",
        "color": "Tan",
        "size": "43",
        "price": 159,
        "quantity": 25,
        "image": "brogues-tan.jpg"
      }
    ]
  },
  {
    "id": "CANVAS-033",
    "name": "High-Top Canvas Sneakers",
    "brand": "Converse",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Classic high-top canvas sneakers featuring thick double-stitched cotton canvas, protective rubber toe cap, metal eyelets, and vulcanized rubber sole.",
    "material": "Cotton Canvas & Vulcanized Rubber",
    "gender": "unisex",
    "price": 65,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 542,
    "image": "high-tops.jpg",
    "variants": [
      {
        "sku": "CANVAS-033-BLA-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 65,
        "quantity": 25,
        "image": "high-tops.jpg"
      },
      {
        "sku": "CANVAS-033-BLA-43",
        "label": "Black / 43",
        "color": "Black",
        "size": "43",
        "price": 65,
        "quantity": 25,
        "image": "high-tops.jpg"
      }
    ]
  },
  {
    "id": "SANDAL-034",
    "name": "Sport Utility Sandals",
    "brand": "Teva",
    "category_1": "Footwear",
    "category_2": "Sandals",
    "description": "All-terrain sports utility sandals designed with triple hook-and-loop adjustable webbing straps, contoured EVA footbed, and high-traction rubber tread.",
    "material": "Recycled Polyester Webbing",
    "gender": "unisex",
    "price": 75,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 178,
    "image": "sandals-sport.jpg",
    "variants": [
      {
        "sku": "SANDAL-034-BLA-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 75,
        "quantity": 25,
        "image": "sandals-sport.jpg"
      },
      {
        "sku": "SANDAL-034-BLA-43",
        "label": "Black / 43",
        "color": "Black",
        "size": "43",
        "price": 75,
        "quantity": 25,
        "image": "sandals-sport.jpg"
      }
    ]
  },
  {
    "id": "DERBY-035",
    "name": "Classic Derby Shoes",
    "brand": "Ecco",
    "category_1": "Footwear",
    "category_2": "Shoes",
    "description": "Smart casual Derby shoes featuring a clean open-lacing profile in smooth box-calf leather, complete with comfortable padded collar and micro-foam insole.",
    "material": "Box-Calf Leather Upper",
    "gender": "men",
    "price": 139,
    "currency": "EUR",
    "rating_value": 4.4,
    "rating_count": 105,
    "image": "derby-shoes.jpg",
    "variants": [
      {
        "sku": "DERBY-035-BLA-42",
        "label": "Black / 42",
        "color": "Black",
        "size": "42",
        "price": 139,
        "quantity": 25,
        "image": "derby-shoes.jpg"
      },
      {
        "sku": "DERBY-035-BLA-43",
        "label": "Black / 43",
        "color": "Black",
        "size": "43",
        "price": 139,
        "quantity": 25,
        "image": "derby-shoes.jpg"
      }
    ]
  },
  {
    "id": "RAIN-036",
    "name": "Waterproof Rain Boots",
    "brand": "Hunter",
    "category_1": "Footwear",
    "category_2": "Boots",
    "description": "Bright classic waterproof rain boots manufactured in heavy-duty natural vulcanized rubber, offering a deep tread and comfortable jersey fabric inner lining.",
    "material": "100% Natural Rubber",
    "gender": "unisex",
    "price": 115,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 192,
    "image": "rain-boots.jpg",
    "variants": [
      {
        "sku": "RAIN-036-YEL-41",
        "label": "Yellow / 41",
        "color": "Yellow",
        "size": "41",
        "price": 115,
        "quantity": 25,
        "image": "rain-boots.jpg"
      },
      {
        "sku": "RAIN-036-YEL-42",
        "label": "Yellow / 42",
        "color": "Yellow",
        "size": "42",
        "price": 115,
        "quantity": 25,
        "image": "rain-boots.jpg"
      }
    ]
  },
  {
    "id": "SCARF-037",
    "name": "Soft Wool Scarf",
    "brand": "Acne Studios",
    "category_1": "Accessories",
    "category_2": "Scarves",
    "description": "Luxurious knit scarf woven from extra-fine baby alpaca wool, featuring elegant fringed borders and a generous length for versatile winter styling.",
    "material": "100% Alpaca Wool",
    "gender": "unisex",
    "price": 180,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 64,
    "image": "scarf-wool.jpg",
    "variants": [
      {
        "sku": "SCARF-037-GRE-GRY",
        "label": "Grey",
        "color": "Grey",
        "size": "One Size",
        "price": 180,
        "quantity": 25,
        "image": "scarf-wool.jpg"
      }
    ]
  },
  {
    "id": "SUNGLASS-038",
    "name": "Tortoiseshell Sunglasses",
    "brand": "Ray-Ban",
    "category_1": "Accessories",
    "category_2": "Sunglasses",
    "description": "Retro-inspired round tortoiseshell sunglasses crafted with premium acetate frames and impact-resistant polarized lenses providing 100% UV protection.",
    "material": "Acetate Frame & Polarized Glass",
    "gender": "unisex",
    "price": 160,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 234,
    "image": "sunglasses-tortoise.jpg",
    "variants": [
      {
        "sku": "SUNGLASS-038-TOR-TOR",
        "label": "Tortoiseshell",
        "color": "Tortoiseshell",
        "size": "One Size",
        "price": 160,
        "quantity": 25,
        "image": "sunglasses-tortoise.jpg"
      }
    ]
  },
  {
    "id": "BEANIE-039",
    "name": "Ribbed Wool Beanie",
    "brand": "Carhartt WIP",
    "category_1": "Accessories",
    "category_2": "Hats",
    "description": "Classic cuffed ribbed beanie hat knit from high-grade organic merino wool. Soft, breathable, and designed for optimal warmth during cooler months.",
    "material": "100% Merino Wool",
    "gender": "unisex",
    "price": 29.99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 412,
    "image": "beanie-ribbed.jpg",
    "variants": [
      {
        "sku": "BEANIE-039-BLA-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 29.99,
        "quantity": 25,
        "image": "beanie-ribbed.jpg"
      }
    ]
  },
  {
    "id": "GLOVE-040",
    "name": "Warm Leather Gloves",
    "brand": "Hestra",
    "category_1": "Accessories",
    "category_2": "Gloves",
    "description": "Elegant cold-weather gloves tailored in soft-grade Nappa leather, lined with ultra-warm cashmere blend fabric and touch-screen compatible finger pads.",
    "material": "Nappa Leather & Cashmere Lining",
    "gender": "unisex",
    "price": 99,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 82,
    "image": "gloves-leather.jpg",
    "variants": [
      {
        "sku": "GLOVE-040-BLA-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 99,
        "quantity": 25,
        "image": "gloves-leather.jpg"
      }
    ]
  },
  {
    "id": "FEDORA-041",
    "name": "Wide-Brim Felt Fedora",
    "brand": "Brixton",
    "category_1": "Accessories",
    "category_2": "Hats",
    "description": "Structured wide-brim fedora hat formed in premium stiff-brushed wool felt, detailed with a slim matching leather band and internal sweatband.",
    "material": "100% Wool Felt & Leather Trim",
    "gender": "unisex",
    "price": 89,
    "currency": "EUR",
    "rating_value": 4.3,
    "rating_count": 56,
    "image": "fedora-felt.jpg",
    "variants": [
      {
        "sku": "FEDORA-041-BRO-BRN",
        "label": "Brown",
        "color": "Brown",
        "size": "One Size",
        "price": 89,
        "quantity": 25,
        "image": "fedora-felt.jpg"
      }
    ]
  },
  {
    "id": "TOTE-042",
    "name": "Canvas Everyday Tote Bag",
    "brand": "L.L. Bean",
    "category_1": "Accessories",
    "category_2": "Bags",
    "description": "Sturdy and spacious everyday tote bag constructed from heavyweight 16oz cotton canvas, featuring comfortable wide shoulder straps and a zip interior pocket.",
    "material": "16oz Heavy Cotton Canvas",
    "gender": "unisex",
    "price": 45,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 589,
    "image": "tote-canvas.jpg",
    "variants": [
      {
        "sku": "TOTE-042-WHI-WHT",
        "label": "White",
        "color": "White",
        "size": "One Size",
        "price": 45,
        "quantity": 25,
        "image": "tote-canvas.jpg"
      }
    ]
  },
  {
    "id": "CAP-043",
    "name": "Canvas Baseball Cap",
    "brand": "Patagonia",
    "category_1": "Accessories",
    "category_2": "Hats",
    "description": "Unstructured 6-panel baseball cap built from durable washed cotton twill. Features embroidered ventilation eyelets and an adjustable brass metal clasp.",
    "material": "100% Cotton Twill",
    "gender": "unisex",
    "price": 35,
    "currency": "EUR",
    "rating_value": 4.6,
    "rating_count": 153,
    "image": "cap-baseball.jpg",
    "variants": [
      {
        "sku": "CAP-043-NAV-NVY",
        "label": "Navy",
        "color": "Navy",
        "size": "One Size",
        "price": 35,
        "quantity": 25,
        "image": "cap-baseball.jpg"
      }
    ]
  },
  {
    "id": "SOCK-044",
    "name": "Patterned Cotton Crew Socks",
    "brand": "Happy Socks",
    "category_1": "Accessories",
    "category_2": "Socks",
    "description": "Playful multipack of crew socks knit in high-grade combed cotton with elastic arch compression support and reinforced heels for maximum durability.",
    "material": "80% Combed Cotton 17% Polyamide 3% Elastane",
    "gender": "unisex",
    "price": 14.99,
    "currency": "EUR",
    "rating_value": 4.5,
    "rating_count": 201,
    "image": "socks-cotton.jpg",
    "variants": [
      {
        "sku": "SOCK-044-MIX-MIX",
        "label": "Mixed",
        "color": "Mixed",
        "size": "One Size",
        "price": 14.99,
        "quantity": 25,
        "image": "socks-cotton.jpg"
      }
    ]
  },
  {
    "id": "UMBRELLA-045",
    "name": "Compact Windproof Umbrella",
    "brand": "Repel",
    "category_1": "Accessories",
    "category_2": "Bags",
    "description": "Compact travel umbrella featuring a robust 9-rib windproof frame, water-repellent Teflon coated canopy, and an ergonomic automatic open-close button.",
    "material": "Teflon-Coated Polyester & Steel Frame",
    "gender": "unisex",
    "price": 32,
    "currency": "EUR",
    "rating_value": 4.7,
    "rating_count": 412,
    "image": "umbrella-compact.jpg",
    "variants": [
      {
        "sku": "UMBRELLA-045-BLA-BLK",
        "label": "Black",
        "color": "Black",
        "size": "One Size",
        "price": 32,
        "quantity": 25,
        "image": "umbrella-compact.jpg"
      }
    ]
  },
  {
    "id": "POUCH-046",
    "name": "Travel Tech Pouch",
    "brand": "Peak Design",
    "category_1": "Accessories",
    "category_2": "Bags",
    "description": "Organized electronics travel organizer crafted in water-resistant poly ripstop, packed with elastic loops, mesh pockets, and cable pass-throughs.",
    "material": "200D Recycled Nylon Ripstop",
    "gender": "unisex",
    "price": 59.95,
    "currency": "EUR",
    "rating_value": 4.8,
    "rating_count": 187,
    "image": "pouch-travel.jpg",
    "variants": [
      {
        "sku": "POUCH-046-GRE-GRY",
        "label": "Grey",
        "color": "Grey",
        "size": "One Size",
        "price": 59.95,
        "quantity": 25,
        "image": "pouch-travel.jpg"
      }
    ]
  }
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category_1 === category);
}
