// Generates data/catalog.ts and data/images.ts from the source catalog.csv.
// Run: node scripts/generate-data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const SRC_CSV = path.resolve(root, '../criteo-dynamic-test-shop/catalog.csv');
const IMAGES_DIR = path.resolve(root, 'assets/products');

function parseLine(line) {
  const out = [];
  let cur = '';
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (q) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') { q = false; }
      else { cur += c; }
    } else {
      if (c === ',') { out.push(cur); cur = ''; }
      else if (c === '"') { q = true; }
      else { cur += c; }
    }
  }
  out.push(cur);
  return out;
}

function parseCSV(txt) {
  const lines = txt.replace(/\r/g, '').split('\n').filter((l) => l.length > 0);
  const headers = parseLine(lines[0]);
  return lines.slice(1).map((line) => {
    const vals = parseLine(line);
    const row = {};
    headers.forEach((h, i) => (row[h] = vals[i] !== undefined ? vals[i] : ''));
    return row;
  });
}

const basename = (p) => String(p || '').split('/').pop();

// Parse the catalog up front so we only bundle images it actually references.
const rows = parseCSV(fs.readFileSync(SRC_CSV, 'utf8'));
const referenced = new Set(rows.map((r) => basename(r.image)).filter(Boolean));

// --- images.ts ---
// Only include images referenced by the catalog. Bundling orphan files bloats
// the app and can cause Android resource collisions (see the guard below).
const available = new Set(
  fs.readdirSync(IMAGES_DIR).filter((f) => /\.(jpg|jpeg|png)$/i.test(f))
);
const imageFiles = [...referenced].filter((f) => available.has(f)).sort();

const missing = [...referenced].filter((f) => !available.has(f));
if (missing.length) {
  throw new Error(`Missing image assets referenced by catalog: ${missing.join(', ')}`);
}

// React Native flattens bundled assets into Android drawable resources named
// after the path with the extension stripped and non-alphanumerics removed
// (e.g. assets/products/watch-gold.png -> assets_products_watchgold). Two files
// that differ only by extension collide during mergeReleaseResources. Fail here
// with a clear message instead of deep in a cloud Gradle build.
// Android's AAPT compiles assets by their file extension, not their content.
// A JPEG saved as ".png" (or vice versa) makes AAPT fail with
// "file failed to compile". Detect the real type from magic bytes and fail here.
function realImageExt(file) {
  const head = fs.readFileSync(path.join(IMAGES_DIR, file)).subarray(0, 4);
  if (head[0] === 0x89 && head[1] === 0x50) return 'png'; // \x89PNG
  if (head[0] === 0xff && head[1] === 0xd8) return 'jpg'; // JPEG SOI
  return null;
}

const flat = (f) => f.replace(/\.[^.]*$/, '').replace(/[^a-z0-9]/gi, '').toLowerCase();
const seen = new Map();
for (const f of imageFiles) {
  const declared = f.split('.').pop().toLowerCase().replace('jpeg', 'jpg');
  const actual = realImageExt(f);
  if (actual && declared !== actual) {
    throw new Error(
      `Image "${f}" is declared .${declared} but its content is ${actual.toUpperCase()}. ` +
        `Android's AAPT will reject it. Re-encode it to a real .${declared} ` +
        `(e.g. sips -s format ${declared === 'jpg' ? 'jpeg' : 'png'} <file> --out <file>).`
    );
  }
  const key = flat(f);
  if (seen.has(key)) {
    throw new Error(
      `Android drawable name collision: "${seen.get(key)}" and "${f}" both flatten to "${key}". ` +
        'Rename one source image so basenames are unique after extension removal.'
    );
  }
  seen.set(key, f);
}

const imagesTs =
  '// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.\n' +
  '// Static require() map so Metro can bundle product images.\n' +
  'export const IMAGES: Record<string, number> = {\n' +
  imageFiles.map((f) => `  ${JSON.stringify(f)}: require('../assets/products/${f}'),`).join('\n') +
  '\n};\n\n' +
  "export function productImage(file?: string): number | undefined {\n" +
  '  if (!file) return undefined;\n' +
  '  return IMAGES[file];\n' +
  '}\n';

fs.writeFileSync(path.resolve(root, 'data/images.ts'), imagesTs);

// --- catalog.ts ---
const byId = new Map();
for (const r of rows) {
  if (!byId.has(r.id)) {
    byId.set(r.id, {
      id: r.id,
      name: r.name,
      brand: r.brand,
      category_1: r.category_1,
      category_2: r.category_2,
      description: r.description,
      material: r.material,
      gender: r.gender,
      price: Number(r.price),
      currency: 'EUR',
      rating_value: Number(r.rating_value) || undefined,
      rating_count: Number(r.rating_count) || undefined,
      image: basename(r.image),
      variants: [],
    });
  }
  const p = byId.get(r.id);
  p.variants.push({
    sku: r.sku,
    label: r.variant,
    color: r.color,
    size: r.size,
    price: Number(r.price),
    quantity: Number(r.quantity) || 0,
    image: basename(r.image),
  });
}

const products = [...byId.values()];
const categories = [...new Set(products.map((p) => p.category_1))];

const catalogTs =
  '// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.\n\n' +
  'export type Variant = {\n' +
  '  sku: string;\n  label: string;\n  color: string;\n  size: string;\n' +
  '  price: number;\n  quantity: number;\n  image: string;\n};\n\n' +
  'export type Product = {\n' +
  '  id: string;\n  name: string;\n  brand: string;\n  category_1: string;\n  category_2: string;\n' +
  '  description: string;\n  material: string;\n  gender: string;\n  price: number;\n  currency: string;\n' +
  '  rating_value?: number;\n  rating_count?: number;\n  image: string;\n  variants: Variant[];\n};\n\n' +
  `export const CATEGORIES: string[] = ${JSON.stringify(categories)};\n\n` +
  `export const PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};\n\n` +
  'export function getProduct(id: string): Product | undefined {\n' +
  '  return PRODUCTS.find((p) => p.id === id);\n}\n\n' +
  'export function productsByCategory(category: string): Product[] {\n' +
  '  return PRODUCTS.filter((p) => p.category_1 === category);\n}\n';

fs.writeFileSync(path.resolve(root, 'data/catalog.ts'), catalogTs);

console.log(`Generated data/catalog.ts (${products.length} products, ${categories.length} categories) and data/images.ts (${imageFiles.length} images).`);
